Main page
dicePoker/dicePoker pull request #10
Opened 2021-09-13 19:07 UTC by AngryFennec

2021-09-15 10:19 UTC, KirillGrom approved these changes

2021-09-15 15:07 UTC, gisma87 approved these changes

2021-09-20 06:54 UTC, rnkupov requested changes

2021-09-20 06:54 UTC, rnkupov commented on src/components/Table/Table.tsx
> +                  return (
return лишний

2021-09-20 06:54 UTC, rnkupov commented on src/components/Table/Table.tsx
> +                  return (
return лишний

2021-09-20 06:54 UTC, rnkupov commented on src/components/Table/Table.tsx
> +          {props.gameController.phase === 1
данные которые мапаются лючше зарание вычеслить в переменную и не делать ифу в jsx

2021-09-20 06:54 UTC, rnkupov commented on src/components/Table/Table.tsx
> +                      return (
return лишний

2021-09-20 06:54 UTC, rnkupov commented on src/components/Table/Table.tsx
> +                      return (
return лишний

2021-09-20 06:54 UTC, rnkupov commented on src/components/Table/Table.tsx
> +                  ? item.firstPhasePoints.map((val, index) => {
данные которые мапаются лючше зарание вычеслить в переменную и не делать ифу в jsx

2021-09-20 06:54 UTC, rnkupov commented on src/controllers/DrawController.ts
> +    //this.pixelRatio = window.devicePixelRatio || 1;
закоментированный код надо удалить

2021-09-20 06:54 UTC, rnkupov commented on src/controllers/GameController.ts
> +    console.log(evt.target.dataset.comb);
console.log надо удалить

2021-09-20 06:54 UTC, rnkupov commented on src/controllers/GameController.ts
> +    console.log(cubeValues);
console.log надо удалить

2021-09-20 06:54 UTC, rnkupov commented on src/controllers/DrawController.ts
> +  // рисуем верхний ряд
кажется неправильный коммментарий

2021-09-22 07:27 UTC, rnkupov approved these changes

2021-09-22 08:27 UTC, merged