Хук для web API (автоматическая пауза)
dicePoker/dicePoker pull request #11
Opened 2021-09-14 19:30 UTC by KirillGrom

2021-09-14 19:31 UTC, KirillGrom commented
Когда вольют https://github.com/dicePoker/dicePoker/pull/10 подлить в ветку и перенести Pause в MainPage

2021-09-15 14:59 UTC, gisma87 approved these changes

2021-09-20 06:56 UTC, rnkupov requested changes

2021-09-20 06:56 UTC, rnkupov commented on src/pages/SignIn/SignIn.tsx
> +      <Modal isShow={isShowModal}>
компонент паузы точно нужен только на странице авторизации?

2021-09-20 07:13 UTC, KirillGrom commented on src/pages/SignIn/SignIn.tsx
> +      <Modal isShow={isShowModal}>
@rnkupov  он там вообще не нужен , он нужен на mainpage  , но она не влита .

2021-09-21 18:21 UTC, AngryFennec approved these changes

2021-09-22 07:28 UTC, rnkupov approved these changes

2021-09-25 18:44 UTC, merged