Страница регистрации
dicePoker/dicePoker pull request #2
Opened 2021-08-16 05:02 UTC by KirillGrom

2021-08-16 10:12 UTC, AngryFennec commented on src/components/App/App.scss
> +}
Кажется, нужен линтер - или мы очень быстро вскроемся со своими предпочтениями по отступам

2021-08-16 10:13 UTC, AngryFennec commented on src/components/signUpForm/signUpForm.tsx
> +        <TextField  type="text"  label="Имя"/>
полям пригодятся айдишники и неймы

2021-08-16 11:12 UTC, KirillGrom commented on src/components/App/App.scss
> +}
Да , я добавлю

2021-08-16 11:12 UTC, KirillGrom commented on src/components/signUpForm/signUpForm.tsx
> +        <TextField  type="text"  label="Имя"/>
Зачем айди?

2021-08-16 16:11 UTC, AngryFennec commented on src/components/signUpForm/signUpForm.tsx
> +        <TextField  type="text"  label="Имя"/>
Ладно, можем без айди) для точечной валидации можем рефы использовать

2021-08-17 03:41 UTC, gisma87 approved these changes

2021-08-17 03:42 UTC, gisma87 approved these changes

2021-08-17 06:32 UTC, AngryFennec approved these changes

2021-08-17 10:18 UTC, rnkupov requested changes

2021-08-17 10:18 UTC, rnkupov commented on src/components/SignUpForm/SignUpForm.scss
> +  &__title {
стили для вложенных блоках принято разделять пустой строкой

2021-08-17 10:18 UTC, rnkupov commented on src/components/SignUpForm/SignUpForm.tsx
> +const useStyles = makeStyles((theme) => ({
задать стилизацию компонентам из библиотеки лучше в одном месте на проекте

2021-08-17 10:18 UTC, rnkupov commented on src/pages/SignUp/SignUp.tsx
> +export default function  SignUp(): JSX.Element {
лучше просто стрелочной функцией и экспортировать через export для единообразия в export/import

2021-08-17 10:18 UTC, rnkupov commented on src/components/SignUpForm/SignUpForm.tsx
> +export default function SignUpForm(): JSX.Element {
лучше просто стрелочной функцией и экспортировать через export для единообразия в export/import

2021-08-17 10:18 UTC, rnkupov commented on src/components/SignUpForm/SignUpForm.scss
> +    font-family: 'Roboto', sans-serif;
шрифты лучше повесить на корневой элемент страницы

2021-08-18 05:17 UTC, KirillGrom commented on src/components/SignUpForm/SignUpForm.tsx
> +const useStyles = makeStyles((theme) => ({
Нужно влить ветку sign-in там это поправлено

2021-08-18 13:36 UTC, rnkupov commented
посмотрю после влития https://github.com/dicePoker/dicePoker/pull/3#pullrequestreview-732871387 и ребейза

2021-08-18 16:56 UTC, rnkupov requested changes
надо настроить prettier и прогнать через него весть проект для едиообразия кода

2021-08-18 19:07 UTC, rnkupov approved these changes

2021-08-19 03:57 UTC, merged