Страница авторизации
dicePoker/dicePoker pull request #3
Opened 2021-08-16 06:16 UTC by KirillGrom

2021-08-16 10:08 UTC, AngryFennec commented on src/components/signInForm/signInForm.tsx
> +import './signInForm.scss'
предлагаю именовать файлы с заглавных букв, папки тоже

2021-08-17 06:33 UTC, AngryFennec approved these changes

2021-08-17 10:15 UTC, rnkupov requested changes
мне очень понравилось что настроили eslint
обсудите с командой конфиг
и еще было бы круто настроит prettier

2021-08-17 10:15 UTC, rnkupov commented on .eslintrc.json
> +        "plugin:@typescript-eslint/recommended",
конфиги eslint лучше не смешивать
надо командой выбрать один recommended или airbnb

2021-08-17 10:15 UTC, rnkupov commented on src/components/App/App.tsx
> +export default function App(): JSX.Element {
лучше просто стрелочной функцией и экспортировать через export для единообразия в export/import
так же тогда можно будет return не писать

2021-08-17 10:15 UTC, rnkupov commented on src/components/SignInForm/SignInForm.scss
> +  width: 214px;
стили для вложенных блоках принято разделять пустой строкой

2021-08-17 10:15 UTC, rnkupov commented on src/components/SignInForm/SignInForm.scss
> +
лишняя строка

2021-08-17 10:15 UTC, rnkupov commented on src/components/SignInForm/SignInForm.scss
> +    font-family: Roboto, sans-serif;
шрифты лучше повесить на корневой элемент страницы

2021-08-17 10:15 UTC, rnkupov commented on src/components/SignInForm/SignInForm.tsx
> +const useStyles = makeStyles((theme) => ({
задать стилизацию компонентам из библиотеки лучше в одном месте на проекте

2021-08-17 10:15 UTC, rnkupov commented on src/components/SignInForm/SignInForm.tsx
> +export default function SignInForm(): JSX.Element {
лучше просто стрелочной функцией и экспортировать через export для единообразия в export/import

2021-08-17 10:15 UTC, rnkupov commented on src/components/SignInForm/SignInForm.tsx
> +          ВОЙТИ
лучше сделать uppercase с помощью css

2021-08-17 10:15 UTC, rnkupov commented on src/pages/SignIn/SignIn.tsx
> +export default function SignIn(): JSX.Element {
лучше просто стрелочной функцией и экспортировать через export для единообразия в export/import

2021-08-17 19:00 UTC, rnkupov commented on .eslintrc.json
> +        "plugin:@typescript-eslint/recommended",
тут можно посмотреть состав базового конфига airbnb
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/index.js
тут расширенный который ты поставил
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/index.js
вот тут можно посмотреть конфиг ts
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.ts
плюс важен порядок конфигов

2021-08-18 13:35 UTC, rnkupov requested changes
осталось только настроить prettier и вернуть кавычки обратно

2021-08-18 13:35 UTC, rnkupov commented on src/components/App/App.scss
> +  font-family: "Roboto", sans-serif;
давай настроим prettier на одинарные кавычки

2021-08-18 16:09 UTC, merged