Profile
dicePoker/dicePoker pull request #4
Opened 2021-08-18 16:41 UTC by AngryFennec

2021-08-19 03:48 UTC, gisma87 approved these changes

2021-08-19 03:58 UTC, KirillGrom commented on src/components/Profile/Profile.tsx
> +export default function Profile(): JSX.Element {
Давай поменяем на стрелочную )) что бы все одинаково было

2021-08-19 03:58 UTC, KirillGrom commented on src/components/Profile/Profile.tsx
> +            name="first_name"
Давай будем писать в кемал кейсе , а потом через нормализатор прогоним перед отправкой .

2021-08-21 07:41 UTC, rnkupov requested changes

2021-08-21 07:41 UTC, rnkupov commented on src/components/Profile/Profile.tsx
> +const useStyles = makeStyles(theme => ({
задать стилизацию компонентам из библиотеки лучше в одном месте на проекте
Кирилл файл уже создавал

2021-08-21 07:41 UTC, rnkupov commented on src/components/Profile/Profile.tsx
> +          <TextField
данные по текстовым полям лучше сложить в массив и его проитерировать в jsx

2021-08-23 10:46 UTC, rnkupov approved these changes

2021-08-23 10:58 UTC, merged