Redux & loader
dicePoker/dicePoker pull request #6
Opened 2021-08-31 16:04 UTC by gisma87

2021-09-01 07:28 UTC, KirillGrom commented on src/components/Loader/Loader.scss
> +  $color-1: #e8ddb5;
Привет , зачем дублировать цвет ?

2021-09-01 07:31 UTC, KirillGrom commented on src/redux/actions/actions.ts
> +export const loadingTrue = (): ActionLoadingTrue => {
Привет , зачем в конец добавлять True ? Мне кажется лучше переименовать на что то более понятное .  Например: loadingSuccess

2021-09-01 07:31 UTC, KirillGrom commented on src/redux/actions/actions.ts
> +export const loadingFalse = (): ActionLoadingFalse => {
Привет , зачем в конец добавлять True ? Мне кажется лучше переименовать на что то более понятное . Например: loadingFailed

2021-09-01 07:36 UTC, KirillGrom commented on src/redux/reducer/reducer.ts
> +  loading: 0,
Привет, лучше сделать loading true|false, это более читаемо. Любой разраб поймет что есть только два состояния

2021-09-01 07:37 UTC, KirillGrom commented on src/service/ApiService.js
> +        resolve([
Привет , может вынесем в константу ?

2021-09-01 07:39 UTC, KirillGrom commented on src/components/Loader/Loader.scss
> +  $color-3: #e8ddb5;
Привет , зачем дублировать цвет ?

2021-09-01 16:09 UTC, gisma87 commented on src/redux/reducer/reducer.ts
> +  loading: 0,
Запросов может быть несколько. Если состояние будет дуальным, то при окончании первого запроса, loading выставится в false. Хотя это не будет соответствовать действительности. 
Прибавлять 1 при открытии и отнимать при закрытии  простой способ, который отлично работает в случаях когда не нужно знать, какой именно запрос выполняется.

2021-09-01 16:16 UTC, gisma87 commented on src/service/ApiService.js
> +        resolve([
Как ты любишь выносить **временные** данные в константу. 
В рабочих проектах тоже так делаешь? Это просто временные данные, чтобы было видно, что всё работает. Они не нужны. 
getUsers это тестовый запрос. Его удалить нужно.
Удалить?

Это как в прошлый раз ты пожаловался на инлайновые стили в <div style{...}>Главная страница </div>. Если бы там вынести стили в класс, то потом, когда удалять нужно будет то ещё придётся искать стили в другом файле, вместо того, чтобы просто снести одну строку.

2021-09-01 16:26 UTC, gisma87 commented on src/components/Loader/Loader.scss
> +  $color-3: #e8ddb5;
оверинженериг в действии ...
Если нужно чтобы `a=5` и `b=5`, это не значит, что ради "*оптимизации*" записывать так: `a=5; b=a.`
`$color-1, $color-2, $color-3` это переменные. И да, они имеют один цвет, но это не обязательно.

2021-09-01 16:46 UTC, KirillGrom commented on src/service/ApiService.js
> +        resolve([
Да , даже временные константы выносим

2021-09-01 16:47 UTC, KirillGrom commented on src/service/ApiService.js
> +        resolve([
Зачем нужен этот мусар ?

2021-09-01 16:49 UTC, KirillGrom commented on src/components/Loader/Loader.scss
> +  $color-3: #e8ddb5;
А понял , ок

2021-09-01 16:50 UTC, KirillGrom commented on src/redux/reducer/reducer.ts
> +  loading: 0,
А понял , ну ок .

2021-09-05 16:30 UTC, KirillGrom approved these changes

2021-09-08 16:46 UTC, AngryFennec approved these changes

2021-09-09 07:13 UTC, rnkupov requested changes

2021-09-09 07:13 UTC, rnkupov commented on src/components/Loader/Loader.tsx
> +    <div className={'loader ' + className}>
лучше использовать шаблонные строки для формирования className

2021-09-09 07:13 UTC, rnkupov commented on src/pages/Dashboard/Dashboard.tsx
> +  const usersData = useSelector((state: StateTypes) => state.users);
если здесь задать дефолтным значением пустой массив то ниже не надо будет делать проверку на наличие данных

2021-09-09 10:41 UTC, gisma87 commented on src/components/Loader/Loader.tsx
> +    <div className={'loader ' + className}>
исправил

2021-09-09 10:42 UTC, gisma87 commented on src/pages/Dashboard/Dashboard.tsx
> +  const usersData = useSelector((state: StateTypes) => state.users);
убрал проверку на наличие данных. В state.users по умолчанию пустой массив.

2021-09-10 08:18 UTC, rnkupov approved these changes

2021-09-10 11:01 UTC, merged